package com.ocean.pojo;

import java.util.Date;

public class RulePublishDatetime {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_publish_datetime.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_publish_datetime.rule_datetime_id
     *
     * @mbggenerated
     */
    private String ruleDatetimeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_publish_datetime.rule_datetime_start
     *
     * @mbggenerated
     */
    private Date ruleDatetimeStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_publish_datetime.rule_datetime_end
     *
     * @mbggenerated
     */
    private Date ruleDatetimeEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_publish_datetime.rule_money
     *
     * @mbggenerated
     */
    private Byte ruleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_publish_datetime.order_num
     *
     * @mbggenerated
     */
    private Byte orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_publish_datetime.rule_num
     *
     * @mbggenerated
     */
    private Byte ruleNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.id
     *
     * @return the value of rule_publish_datetime.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.id
     *
     * @param id the value for rule_publish_datetime.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_datetime_id
     *
     * @return the value of rule_publish_datetime.rule_datetime_id
     *
     * @mbggenerated
     */
    public String getRuleDatetimeId() {
        return ruleDatetimeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_datetime_id
     *
     * @param ruleDatetimeId the value for rule_publish_datetime.rule_datetime_id
     *
     * @mbggenerated
     */
    public void setRuleDatetimeId(String ruleDatetimeId) {
        this.ruleDatetimeId = ruleDatetimeId == null ? null : ruleDatetimeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_datetime_start
     *
     * @return the value of rule_publish_datetime.rule_datetime_start
     *
     * @mbggenerated
     */
    public Date getRuleDatetimeStart() {
        return ruleDatetimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_datetime_start
     *
     * @param ruleDatetimeStart the value for rule_publish_datetime.rule_datetime_start
     *
     * @mbggenerated
     */
    public void setRuleDatetimeStart(Date ruleDatetimeStart) {
        this.ruleDatetimeStart = ruleDatetimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_datetime_end
     *
     * @return the value of rule_publish_datetime.rule_datetime_end
     *
     * @mbggenerated
     */
    public Date getRuleDatetimeEnd() {
        return ruleDatetimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_datetime_end
     *
     * @param ruleDatetimeEnd the value for rule_publish_datetime.rule_datetime_end
     *
     * @mbggenerated
     */
    public void setRuleDatetimeEnd(Date ruleDatetimeEnd) {
        this.ruleDatetimeEnd = ruleDatetimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_money
     *
     * @return the value of rule_publish_datetime.rule_money
     *
     * @mbggenerated
     */
    public Byte getRuleMoney() {
        return ruleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_money
     *
     * @param ruleMoney the value for rule_publish_datetime.rule_money
     *
     * @mbggenerated
     */
    public void setRuleMoney(Byte ruleMoney) {
        this.ruleMoney = ruleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.order_num
     *
     * @return the value of rule_publish_datetime.order_num
     *
     * @mbggenerated
     */
    public Byte getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.order_num
     *
     * @param orderNum the value for rule_publish_datetime.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Byte orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_num
     *
     * @return the value of rule_publish_datetime.rule_num
     *
     * @mbggenerated
     */
    public Byte getRuleNum() {
        return ruleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_num
     *
     * @param ruleNum the value for rule_publish_datetime.rule_num
     *
     * @mbggenerated
     */
    public void setRuleNum(Byte ruleNum) {
        this.ruleNum = ruleNum;
    }
}