package com.ocean.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class RulePublishDatetime {

    private Long id;
    private String ruleDatetimeId;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date ruleDatetimeStart;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date ruleDatetimeEnd;
    private Byte ruleMoney;
    private Byte orderNum;
    private Byte ruleNum;

    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }


    public String getRuleDatetimeId() {
        return ruleDatetimeId;
    }

    public void setRuleDatetimeId(String ruleDatetimeId) {
        this.ruleDatetimeId = ruleDatetimeId == null ? null : ruleDatetimeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_datetime_start
     *
     * @return the value of rule_publish_datetime.rule_datetime_start
     *
     * @mbggenerated
     */
    public Date getRuleDatetimeStart() {
        return ruleDatetimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_datetime_start
     *
     * @param ruleDatetimeStart the value for rule_publish_datetime.rule_datetime_start
     *
     * @mbggenerated
     */
    public void setRuleDatetimeStart(Date ruleDatetimeStart) {
        this.ruleDatetimeStart = ruleDatetimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_datetime_end
     *
     * @return the value of rule_publish_datetime.rule_datetime_end
     *
     * @mbggenerated
     */
    public Date getRuleDatetimeEnd() {
        return ruleDatetimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_datetime_end
     *
     * @param ruleDatetimeEnd the value for rule_publish_datetime.rule_datetime_end
     *
     * @mbggenerated
     */
    public void setRuleDatetimeEnd(Date ruleDatetimeEnd) {
        this.ruleDatetimeEnd = ruleDatetimeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_money
     *
     * @return the value of rule_publish_datetime.rule_money
     *
     * @mbggenerated
     */
    public Byte getRuleMoney() {
        return ruleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_money
     *
     * @param ruleMoney the value for rule_publish_datetime.rule_money
     *
     * @mbggenerated
     */
    public void setRuleMoney(Byte ruleMoney) {
        this.ruleMoney = ruleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.order_num
     *
     * @return the value of rule_publish_datetime.order_num
     *
     * @mbggenerated
     */
    public Byte getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.order_num
     *
     * @param orderNum the value for rule_publish_datetime.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Byte orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_publish_datetime.rule_num
     *
     * @return the value of rule_publish_datetime.rule_num
     *
     * @mbggenerated
     */
    public Byte getRuleNum() {
        return ruleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_publish_datetime.rule_num
     *
     * @param ruleNum the value for rule_publish_datetime.rule_num
     *
     * @mbggenerated
     */
    public void setRuleNum(Byte ruleNum) {
        this.ruleNum = ruleNum;
    }

    @Override
    public String toString() {
        return "RulePublishDatetime{" +
                "id=" + id +
                ", ruleDatetimeId='" + ruleDatetimeId + '\'' +
                ", ruleDatetimeStart=" + ruleDatetimeStart +
                ", ruleDatetimeEnd=" + ruleDatetimeEnd +
                ", ruleMoney=" + ruleMoney +
                ", orderNum=" + orderNum +
                ", ruleNum=" + ruleNum +
                '}';
    }
}