package com.ocean.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class SnatchInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_info.snatch_info_id
     *
     * @mbggenerated
     */
    private Long snatchInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_info.snatch_mobile_number
     *
     * @mbggenerated
     */
    private String snatchMobileNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_info.snatch_user_id
     *
     * @mbggenerated
     */
    private String snatchUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_info.rule_publish_id
     *
     * @mbggenerated
     */
    private String rulePublishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_info.snatch_datetime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date snatchDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_info.is_audit
     *
     * @mbggenerated
     */
    private Byte isAudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_info.audit_datetime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date auditDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column snatch_info.snatch_money
     *
     * @mbggenerated
     */
    private Byte snatchMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_info.snatch_info_id
     *
     * @return the value of snatch_info.snatch_info_id
     *
     * @mbggenerated
     */
    public Long getSnatchInfoId() {
        return snatchInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_info.snatch_info_id
     *
     * @param snatchInfoId the value for snatch_info.snatch_info_id
     *
     * @mbggenerated
     */
    public void setSnatchInfoId(Long snatchInfoId) {
        this.snatchInfoId = snatchInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_info.snatch_mobile_number
     *
     * @return the value of snatch_info.snatch_mobile_number
     *
     * @mbggenerated
     */
    public String getSnatchMobileNumber() {
        return snatchMobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_info.snatch_mobile_number
     *
     * @param snatchMobileNumber the value for snatch_info.snatch_mobile_number
     *
     * @mbggenerated
     */
    public void setSnatchMobileNumber(String snatchMobileNumber) {
        this.snatchMobileNumber = snatchMobileNumber == null ? null : snatchMobileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_info.snatch_user_id
     *
     * @return the value of snatch_info.snatch_user_id
     *
     * @mbggenerated
     */
    public String getSnatchUserId() {
        return snatchUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_info.snatch_user_id
     *
     * @param snatchUserId the value for snatch_info.snatch_user_id
     *
     * @mbggenerated
     */
    public void setSnatchUserId(String snatchUserId) {
        this.snatchUserId = snatchUserId == null ? null : snatchUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_info.rule_publish_id
     *
     * @return the value of snatch_info.rule_publish_id
     *
     * @mbggenerated
     */
    public String getRulePublishId() {
        return rulePublishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_info.rule_publish_id
     *
     * @param rulePublishId the value for snatch_info.rule_publish_id
     *
     * @mbggenerated
     */
    public void setRulePublishId(String rulePublishId) {
        this.rulePublishId = rulePublishId == null ? null : rulePublishId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_info.snatch_datetime
     *
     * @return the value of snatch_info.snatch_datetime
     *
     * @mbggenerated
     */
    public Date getSnatchDatetime() {
        return snatchDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_info.snatch_datetime
     *
     * @param snatchDatetime the value for snatch_info.snatch_datetime
     *
     * @mbggenerated
     */
    public void setSnatchDatetime(Date snatchDatetime) {
        this.snatchDatetime = snatchDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_info.is_audit
     *
     * @return the value of snatch_info.is_audit
     *
     * @mbggenerated
     */
    public Byte getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_info.is_audit
     *
     * @param isAudit the value for snatch_info.is_audit
     *
     * @mbggenerated
     */
    public void setIsAudit(Byte isAudit) {
        this.isAudit = isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_info.audit_datetime
     *
     * @return the value of snatch_info.audit_datetime
     *
     * @mbggenerated
     */
    public Date getAuditDatetime() {
        return auditDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_info.audit_datetime
     *
     * @param auditDatetime the value for snatch_info.audit_datetime
     *
     * @mbggenerated
     */
    public void setAuditDatetime(Date auditDatetime) {
        this.auditDatetime = auditDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column snatch_info.snatch_money
     *
     * @return the value of snatch_info.snatch_money
     *
     * @mbggenerated
     */
    public Byte getSnatchMoney() {
        return snatchMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column snatch_info.snatch_money
     *
     * @param snatchMoney the value for snatch_info.snatch_money
     *
     * @mbggenerated
     */
    public void setSnatchMoney(Byte snatchMoney) {
        this.snatchMoney = snatchMoney;
    }
}