server:
  port: 18085

spring:
    datasource:
        name: test
        url: jdbc:mysql://134.176.110.182:8907/yqdb?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
        username: yqq
        password: DX@yqq0318
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.ocean.pojo
  configuration:
    map-underscore-to-camel-case: true
