package com.ocean.dao;

import com.ocean.pojo.RulePublishDatetime;

public interface RulePublishDatetimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish_datetime
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish_datetime
     *
     * @mbggenerated
     */
    int insert(RulePublishDatetime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish_datetime
     *
     * @mbggenerated
     */
    int insertSelective(RulePublishDatetime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish_datetime
     *
     * @mbggenerated
     */
    RulePublishDatetime selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish_datetime
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RulePublishDatetime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish_datetime
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RulePublishDatetime record);
}