package com.ocean.dao;

import com.ocean.pojo.RulePublish;
import org.springframework.stereotype.Component;

import java.util.List;
@Component
public interface RulePublishMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long rulePublishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish
     *
     * @mbggenerated
     */
    int insert(RulePublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish
     *
     * @mbggenerated
     */
    int insertSelective(RulePublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish
     *
     * @mbggenerated
     */

    RulePublish selectByPrimaryKey(Long rulePublishId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RulePublish record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_publish
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RulePublish record);
     /*插入发布信息*/
    public boolean insertPublist(RulePublish rulePublish);
    List findAllRulePubList();
    public List queryPublishList(RulePublish rulePublish);

    //根据ID查询单个发布详情
     RulePublish selectPublishById(Long rulePublishId);
}