package com.ocean.dao;

import com.ocean.pojo.TStore;

public interface TStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int insert(TStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int insertSelective(TStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    TStore selectByPrimaryKey(String storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_store
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TStore record);
}